spring.application.name=auth-service
# ===============================
# MySQL Database Config
# ===============================
#Shailendra
#spring.datasource.url=jdbc:mysql://localhost:3306/auth?useSSL=false&allowPublicKeyRetrieval=true
#spring.datasource.username=root
#spring.datasource.password=admin
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true

#Shabbir
 spring.datasource.url=jdbc:mysql://localhost:3306/auth?useSSL=false&allowPublicKeyRetrieval=true
 spring.datasource.username=root
 spring.datasource.password=admin
 spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
 spring.jpa.hibernate.ddl-auto=update
 spring.jpa.show-sql=true

# Yash
#spring.datasource.url=jdbc:mysql://localhost:3306/favorite?useSSL=false&allowPublicKeyRetrieval=true
#spring.datasource.username=root
#spring.datasource.password=1234
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true


# ===============================
# Kafka Consumer Config
# ===============================
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=auth-service
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

# ===============================
# JWT Config
# ===============================
jwt.secret=MySuperLongAndRandomSecretKey123456789!

jwt.expiration=3600000

# Server Port
server.port=8087



eureka.client.service-url.defaultZone=http://localhost:8761/eureka/