spring.application.name=auth-service
server.port=8081

#shabbir
spring.datasource.url=jdbc:mysql://localhost:3306/bookdb
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


#shailendra
#spring.datasource.url=jdbc:mysql://localhost:3306/auth
#spring.datasource.username=root
#spring.datasource.password=admin
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true







# Eureka client config
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
# spring.cloud.config.enabled=false

# JWT Config
jwt.secret=mySecretKey12345mySecretKey12345
jwt.expiration=3600000

# Kafka Config
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer


#sportsapp_auth